# -*- coding: utf-8 -*-
"""escalonamento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pkxRMtg_-fcfm73jPKzTS_n_19EdYZ3J

primeiro codigo feito em otimização de dados
"""

def escalona_matriz(nome_arquivo):
    # abre o arquivo e lê
    with open(nome_arquivo, 'r') as f:
        linhas = f.readlines()
        matriz = [list(map(float, linha.strip().split("=")[0].split())) for linha in linhas]
        b = [float(linha.strip().split("=")[1]) for linha in linhas]

    # mostra os valores originais
    print("Matriz de coeficientes original:")
    imprime_matriz(matriz)
    print("Vetor b original:", b)

    # escalona
    linhas = len(matriz) # linhas
    colunas = len(matriz[0]) # colunas
    for j in range(colunas):
        for i in range(j+1, linhas):
            if matriz[j][j] != 0:
                fator = matriz[i][j] / matriz[j][j]
                for k in range(j, colunas):
                    matriz[i][k] -= fator * matriz[j][k]
                b[i] -= fator * b[j]

    # mostra os valores ja escalonados
    print("Matriz de coeficientes escalonada:")
    imprime_matriz(matriz)
    print("Vetor b escalonado:", b)

#imprime os elementos
def imprime_matriz(matriz):
    for linha in matriz:
        for elemento in linha:
            print("{:.2f} ".format(elemento), end="")
        print()

# chama o nome do arquivo para abrir
escalona_matriz('/content/drive/MyDrive/otimização/matriz.txt')